spring.application.name=keycloak-project
server.port=8083

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/elearning-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/elearning-realm/protocol/openid-connect/certs

logging.level.org.springframework.security=DEBUG
logging.level.org.example.keycloakproject=DEBUG

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cours-db